using Newtonsoft.Json;

namespace Demo_04_API_FormsAndSecrets.Models
{
    // This model was generated by using Paste Special / Paste Json as Class,
    // ... and each name modified to adhere to C# naming conventions.
    // The original JSON property names are added in the JsonProperty attributes provided by the Newtonsoft NuGet package

    [JsonObject]
    public class City
    {
        [JsonProperty(PropertyName = "name")]
        public string? Name { get; set; }

        [JsonProperty(PropertyName = "latitude")]
        public float? Latitude { get; set; }

        [JsonProperty(PropertyName = "longitude")]
        public float? Longitude { get; set; }

        [JsonProperty(PropertyName = "country")]
        public string? Country { get; set; }

        [JsonProperty(PropertyName = "population")]
        public int? Population { get; set; }

        [JsonProperty(PropertyName = "is_capital")]
        public bool? IsCapital { get; set; }
    }

}
