namespace Demo_02_API_Intro.Models
{
    // This class was generated by copying a JSON object, and using Edit/Paste Special/Paste Json as Classes
    public class Post // The generated name was "RootObject" but was changed to "Post" to be more descriptive.
    {
        public int userId { get; set; } // These property names MUST be the same as the JSON names
        public int id { get; set; }
        public string title { get; set; }
        public string body { get; set; }
    }
}
